# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all the files in the current directory to the container
COPY . .

# Set the entry point for the container
ENTRYPOINT ["python", "start.py"]
